const DEPARTMENT_USER_ACCOUNT_STATUS = Object.freeze({
  ACTIVE: "active",
  INACTIVE: "inactive",
  DISABLED: "disabled",
});

const DEPARTMENT_IDS = Object.freeze({
  CISF: 1,
  ENGINEERING_CIVIL: 3,
  ENGINEERING_MECHANICAL: 4,
  MARINE: 7,
  TRAFFIC: 9,
});

const WORKFLOW_ROLES = Object.freeze({
  SAFETY_OFFICER: "SAFETY_OFFICER",
  FIRE_SAFETY_OFFICER: "FIRE_SAFETY_OFFICER",
  DY_CONSERVATOR: "Dy. Conservator",
  CISF_ASST_COMMANDANT: "CISF_ASSISTANT_COMMANDANT",
  APPROVAL: "Approval",
});

module.exports = {
    DEPARTMENT_USER_ACCOUNT_STATUS,
    DEPARTMENT_USER_ACCOUNT_STATUS_LIST: Object.values(DEPARTMENT_USER_ACCOUNT_STATUS),
    DEPARTMENT_IDS,
    WORKFLOW_ROLES,
};
